from TRS_backend.ReportClustering.Util.Enumeration import *
def changeEnumToChinese(enum):
    if enum==InputData.PROCEDURE_VECTOR:
        return '复现步骤'
    elif enum==InputData.PROBLEM_VECTOR:
        return '故障类型'
    elif enum==InputData.WIDGET_VECTOR:
        return '问题控件'
    elif enum==InputData.PROBLEM_WIDGET_VECTOR:
        return '问题控件截图'
    elif enum==InputData.OTHER_WIDGET_VECTOR:
        return '其他控件截图'
    elif enum==ClusteringAlgorithm.KMEANS:
        return 'KMeans'
    elif enum==ClusteringAlgorithm.GMM:
        return 'GMM'
    elif enum==ClusteringAlgorithm.BIRCH:
        return 'BIRCH'
    elif enum==ClusteringAlgorithm.DBSCAN:
        return 'DBSCAN'
    elif enum==FileFormat.WORD:
        return 'doc'
    elif enum==FileFormat.PDF:
        return 'pdf'
    elif enum==FileFormat.MARKDOWN:
        return 'markdown'
    elif enum==Reduction.AVERAGE:
        return '均值降维'
    elif enum==Reduction.DIMENSIONAL:
        return 'PCA降维'
    elif enum==State.FINISH:
        return 'State.FINISH'
    elif enum==State.RUNNING:
        return 'State.RUNNING'

def changeChineseToEnum(chinese):
    if chinese=='复现步骤':
        return InputData.PROCEDURE_VECTOR
    elif chinese=='故障类型':
        return InputData.PROBLEM_VECTOR
    elif chinese=='问题控件':
        return InputData.WIDGET_VECTOR
    elif chinese=='问题控件截图':
        return InputData.PROBLEM_WIDGET_VECTOR
    elif chinese=='其他控件截图':
        return InputData.OTHER_WIDGET_VECTOR
    elif chinese=='KMeans':
        return ClusteringAlgorithm.KMEANS
    elif chinese=='GMM':
        return ClusteringAlgorithm.GMM
    elif chinese=='BIRCH':
        return ClusteringAlgorithm.BIRCH
    elif chinese=='DBSCAN':
        return ClusteringAlgorithm.DBSCAN
    elif chinese=='doc':
        return FileFormat.WORD
    elif chinese=='pdf':
        return FileFormat.PDF
    elif chinese=='markdown':
        return FileFormat.MARKDOWN
    elif chinese=='均值降维':
        return Reduction.AVERAGE
    elif chinese=='PCA降维':
        return Reduction.DIMENSIONAL
    elif chinese=='State.FINISH':
        return State.FINISH
    elif chinese=='State.RUNNING':
        return State.RUNNING
